/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FastCron: typeof import('./src/components/fast-cron/src/fast-cron.vue')['default']
    FastRadioGroup: typeof import('./src/components/fast-radio-group/src/fast-radio-group.vue')['default']
    FastSelect: typeof import('./src/components/fast-select/src/fast-select.vue')['default']
    FastTableColumn: typeof import('./src/components/fast-table-column/src/fast-table-column.vue')['default']
    FastUser: typeof import('./src/components/fast-user/src/fast-user.vue')['default']
    IdealAlertInfo: typeof import('./src/components/ideal-alert-info/src/ideal-alert-info.vue')['default']
    IdealAssociateTag: typeof import('./src/components/ideal-associate-tag/src/ideal-associate-tag.vue')['default']
    IdealButtonEvents: typeof import('./src/components/ideal-button-events/src/ideal-button-events.vue')['default']
    IdealCycleSelect: typeof import('./src/components/ideal-cycle-select/src/ideal-cycle-select.vue')['default']
    IdealDetailInfo: typeof import('./src/components/ideal-detail-info/src/ideal-detail-info.vue')['default']
    IdealHorizontalSteps: typeof import('./src/components/ideal-horizontal-steps/src/ideal-horizontal-steps.vue')['default']
    IdealInputSelect: typeof import('./src/components/ideal-input-select/src/ideal-input-select.vue')['default']
    IdealIpInput: typeof import('./src/components/ideal-ip-input/src/ideal-ip-input.vue')['default']
    IdealJsonPreview: typeof import('./src/components/ideal-json-preview/src/ideal-json-preview.vue')['default']
    IdealPriceFooter: typeof import('./src/components/ideal-price-footer/src/ideal-price-footer.vue')['default']
    IdealRegionProject: typeof import('./src/components/ideal-region-project/src/ideal-region-project.vue')['default']
    IdealRegionSelect: typeof import('./src/components/ideal-region-select/src/ideal-region-select.vue')['default']
    IdealReplaceOpen: typeof import('./src/components/ideal-replace-open/src/ideal-replace-open.vue')['default']
    IdealResourcePool: typeof import('./src/components/ideal-resource-pool/src/ideal-resource-pool.vue')['default']
    IdealSearch: typeof import('./src/components/ideal-search/src/ideal-search.vue')['default']
    IdealSelectSearch: typeof import('./src/components/ideal-select-search/src/ideal-select-search.vue')['default']
    IdealSetTableHeader: typeof import('./src/components/ideal-set-table-header/src/ideal-set-table-header.vue')['default']
    IdealStatusIcon: typeof import('./src/components/ideal-status-icon/src/ideal-status-icon.vue')['default']
    IdealTableList: typeof import('./src/components/ideal-table-list/src/ideal-table-list.vue')['default']
    IdealTableOperate: typeof import('./src/components/ideal-table-operate/src/ideal-table-operate.vue')['default']
    IdealTagMultipleSelect: typeof import('./src/components/ideal-tag-multiple-select/src/ideal-tag-multiple-select.vue')['default']
    IdealTagShow: typeof import('./src/components/ideal-tag-show/src/Ideal-tag-show.vue')['default']
    IdealTextCopy: typeof import('./src/components/ideal-text-copy/src/ideal-text-copy.vue')['default']
    IdealUnbindTag: typeof import('./src/components/ideal-unbind-tag/src/ideal-unbind-tag.vue')['default']
    Lang: typeof import('./src/components/lang/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon/src/svg-icon.vue')['default']
  }
}
