// Nginx转发前缀
export const iams = '/iams'
export const api = '/api'
export const adapter = '/adapter'
export const bill = '/bill'
export const bpm = '/bpm'
export const radar = '/radar'
export const log = '/log'
export const info = '/info'
export const local = '/local'
